dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings: '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}
networks:
  sepolia:
    pricefeed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
  mainnet-fork-dev:
    pricefeed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
    verify: False
  